---
- name: get fact
  ios_facts: 
    gather_subset: hardware

- debug: 
    msg: "facts: {{ ansible_facts }}"
  tags: debug

- name: fetch archive status
  ios_command: 
    commands: "show archive status"
  register: show_archive_status

- name: check if there is another archive already running
  fail:
    msg: Stopping because there is another archive download-sw in progress...
  when: not show_archive_status.stdout[0] | regex_search('IDLE')

- debug: 
    msg: "stacks: {{ ansible_facts.net_stacked_models|length }}"
  tags: debug

- set_fact: 
    stack_count: "{{ ansible_facts.net_stacked_models|length }}"
    stack_count_array: []

- set_fact: stack_count_array="{{ stack_count_array + [ item ] }}"
  with_sequence: start=1 end={{ stack_count }}

- debug: 
    msg: "SCA: {{ stack_count_array }}"
  tags: debug

- name: loop through stacks 
  include_tasks: verify.yml
  loop: "{{ stack_count_array }}"
  vars:
    inner_stack_count: "{{ stack_count }}"
    inner_stack_count_array: "{{ stack_count_array }}"
  loop_control:
    loop_var: outer_item